Secondary marketplace
zonkyio/zonky-api pull request #3
Opened 2017-07-25 12:55 UTC by petrvlcek

2017-07-25 14:22 UTC, bobisjan reviewed
Left some comments. I'm happy to see secondary marketplace alive 👍.

PS: I would prefer to split into two separate pull requests - IMHO these commits are not related to each other. Thoughts?

2017-07-25 14:22 UTC, bobisjan commented on .gitignore
> +.idea
IMHO this belongs into the user's global `.gitignore`, as we should not/can not maintain other available editors?

There are some defaults https://github.com/github/gitignore/blob/master/Node.gitignore, some of them maybe included too.

2017-07-25 14:22 UTC, bobisjan commented on README.md
> +You can build and export the documentation locally outside Apiary with a few simple steps. All you need is working Node JS environment on your machine.
I think it's [Node.js](https://nodejs.org/en/).

2017-07-25 14:22 UTC, bobisjan commented on package.json
> +  "main": "index.js",
There is no `index.js`.

2017-07-25 14:22 UTC, bobisjan commented on package.json
> +  "author": "Zonky, s.r.o.",
Are we [Zonky s.r.o.](https://or.justice.cz/ias/ui/rejstrik-$firma?nazev=zonky) without a comma?

2017-07-25 14:22 UTC, bobisjan commented on README.md
> +1. Install project dependencies
First step should be "cloning repository"?

2017-07-25 14:24 UTC, MartinNuc commented on apiary.apib
> +## Listing investments [/smp/investments]
After deploying API gateway this should be part of `/traded-investments` resource. Maybe we could think about using new endpoint right now instead of `smp/*` so third parties don't have to adjust implementation in future?

2017-07-25 17:01 UTC, petrvlcek commented
@bobisjan Thanks for comments. That totally makes sense. I've split changes into two separate pull requests 👍 .

2017-07-25 17:03 UTC, petrvlcek commented on apiary.apib
> +## Listing investments [/smp/investments]
Thanks for pointing out. We will have to clarify this question tomorrow.

2017-07-26 07:28 UTC, mswiech commented on apiary.apib
> +## Listing investments [/smp/investments]
No, this is `/smp/*` prefix was chosen because of future API gateway solution.

2017-08-03 13:22 UTC, JaroslavHolan approved these changes

2017-08-03 13:22 UTC, JaroslavHolan commented on apiary.apib
> +- deadline: `2016-04-19T18:25:41.208+02:00` (string, required) - purchase offer on secondary marketplace will be cancelled after this deadline
In the response on the test environment we have datetime in Zero hour offest format: `"deadline": "2017-08-03T07:42:19.103Z"`

2017-08-03 15:09 UTC, JaroslavHolan commented on apiary.apib
> +## Investor selling his investments [/users/me/traded-investments]
It should be `[/traded-investments]`

2017-08-04 08:29 UTC, JaroslavHolan requested changes

2017-08-04 08:29 UTC, JaroslavHolan commented on apiary.apib
> +- investmentId: 15822 (number, required) - ID of an investment
Application expected `id` not `investmentId`.

2017-08-04 11:41 UTC, petrvlcek commented on apiary.apib
> +## Investor selling his investments [/users/me/traded-investments]
This is going to be renamed. (Internal PR #2220 already exists)

2017-08-04 11:42 UTC, petrvlcek commented on apiary.apib
> +- investmentId: 15822 (number, required) - ID of an investment
This will be also renamed in order to make API more clear.

2017-08-04 19:41 UTC, JaroslavHolan approved these changes

2017-08-08 08:25 UTC, JaroslavHolan commented on apiary.apib
> +## Investor managing his existing offers [/users/me/traded-investments/{investmentId}]
In app we use `/traded-investments/{investmentId}`.

2017-08-08 11:45 UTC, MartinNuc commented on apiary.apib
> +## Investor managing his existing offers [/users/me/traded-investments/{investmentId}]
@JaroslavHolan this is going to be renamed

2017-08-13 21:18 UTC, MartinNuc approved these changes

2017-08-13 21:18 UTC, merged